src/JavaCall.jl
A fix for the macros `@windows` and `@osx` that fail on 0.4.x preventing use by Julia 0.4. 
Removed deprecations
Removed spurious load error messages.
=> Load JVM Cleanup and Fix for 0.4

src/JavaCall.jl
Currently `JClass` isn't consistent with other `J*` types, which results in some confusion (e.g. see discussion in #11). This PR simply renames `JClass` to `JavaClass`, both - avoiding confusion and freeing name `JClass` to be used for `java.lang.Class`.
=> Renaming of JClass to JavaClass

.gitignore, REQUIRE, doc/_config.yml, src/JavaCall.jl, src/reflect.jl, test/runtests.jl
Sometimes, especially when working with Scala, it turns out to be terribly hard to figure out correct method signature. This PR adds a couple of useful functions for listing and inspecting Java methods. Here's an example of usage:
```
julia> listmethods(JString("test"))
72-element Array{JavaObject{symbol("java.lang.reflect.Method")},1}:
boolean equals(java.lang.Object)              
java.lang.String toString()                   
int hashCode()                                
int compareTo(java.lang.Object)               
int compareTo(java.lang.String)               
int indexOf(java.lang.String, int)            
int indexOf(java.lang.String)                 
int indexOf(int)                              
int indexOf(int, int)                         
java.lang.String valueOf(char) …
```
=> Reflection API

doc/methods.md
Introduced the syntax for inner class calling. 
The destroy method is not readily callable, so I changed the invocation.
=> Inner Classes addition examples, and destory clarificaiton

REQUIRE, src/JavaCall.jl
Avoids installing dependency on non-Windows systems.
=> Use conditional REQUIRE statement for WinReg

src/jvm.jl
Calling init() crashes when classpath has not been set explicitly.
This commit fixes the issue by initializing the JVM with the default
classpath when init() is called without any classpath.
=> Fix init() when classpath has not been set

src/convert.jl, test/runtests.jl
Implement `convert` for `ArrayList` and `List` from Julia `Vector`.
It is similar to the existing methods for `HashTable` and `Map`. Except a default of `JObject` specified for the element type parameter.
=> implement `convert` for `ArrayList`

src/JavaCall.jl, src/core.jl, src/reflect.jl, test/runtests.jl
Calling `Class.forName(name)` from JavaCall fails , most likely because default class loader doesn't respect a classpath, however calling `Class.forName(name, true, classLoader)` works fine. This PR provides a convenient wrapper function `class_for_name` for it.
=> class_for_name / Class.forName

src/JavaCall.jl, src/convert.jl, test/runtests.jl
Introduced 2 new functions: 
* `iterator` - same as `collection.iterator()` in  Java
* `narrow` - narrow type of a `JavaObject` to its actual class
`iterator` seems to be very generic, so not exporting it by default. `narrow` seems to be more specific, yet I'm not sure how much intuitive it is, so alternative names are welcome.
=> A bit better iterator API

src/reflect.jl, test/runtests.jl
Currently we can do:
listmethods(foo, "bar")
but not
listmethods(JFoo, "bar")
This PR fixes it.
=> listmethods() for types

src/jvm.jl
On MacOS JDK-9 can be found on ${JAVA_HOME}/lib/server/
=> Compatibility with Java 9

.travis.yml, REQUIRE, appveyor.yml, doc/methods.md, doc/push-gh-pages.jl, src/JavaCall.jl, src/convert.jl, src/core.jl, src/jnienv.jl, src/jvm.jl, src/reflect.jl, test/runtests.jl
Ok, this is a complete overhaul for 0.7.  I have maintained compatibility with 0.6, but dropped compatibility with 0.5.  I've also modernized "runtests.jl".
There were quite a few changes here, so I took the opportunity to clean up some code that I found messy or hard to read.  Of course this is very subjective, so hopefully I didn't go overboard on that account.  The only real change in functionality here is that `@jlimport` now also filters out `(` and `)` characters from its arguments, since in 0.7 Julia will insert those automatically to `getproperty` calls, and Java really doesn't like that.  I took the opportunity to rewrite `@jlimport` slightly to utilize proper multiple dispatch which as been availble on macros since at least 0.6.
On a side note, with this update JDBC should be …
=> Updates for 0.7

src/JavaCall.jl, src/convert.jl, src/core.jl, src/jnienv.jl, src/jvm.jl
This was done quickly and without much care, but I added a `JavaCallError` and replaced most of the error calls with `throw(JavaCallError(str))`.
This should fix the issue where `@error` wasn't throwing errors in the places where originally intended and also do a tiny bit to pave the way for more proper error handling (i.e. coexistence of Julia and Java errors).
=> some slightly better error handling

src/jvm.jl
Hello all.  I've cleaned up the JVM discovery a bit.  First, the standard `JAVA_HOME` locations are now stored in the global constant `JAVA_HOME_CANDIDATES`, making it slightly easier and more transparent for future committers to put new directories there.  Additionally, I have added the directory `/usr/lib/jvm/default` to these, which is the default `JAVA_HOME` on Arch linux (pretty sure this is the standard for modern Java on modern linux distros).
Lastly, the message that tells the user that `libjvm.so` has been loaded has been changed to `@info` so that it can be controlled with logging.  Is there any interest in removing this message entirely?  It seems a little pedantic to tell the user that you are loading the JVM library when JavaCall is loaded, I mean of course it has to load a …
=> improvedi `libjvm` discovery

Project.toml, REQUIRE, src/jvm.jl
Seems pretty silly of us not to have had this already.
Current behavior might be pretty bewildering to anyone who's not constantly reading Julia discourse or Slack, which is not at all ideal.
I also took this opportunity to delete the long since deprecated `REQUIRE` file.
Currently the behavior with unset `JULIA_COPY_STACKS` is so bad that perhaps we should even consider throwing an explicit exception here.
=> added warning in case of unset JULIA_COPY_STACKS variable

.travis.yml, README.md, doc/index.md, src/JavaCall.jl, src/core.jl, src/jvm.jl, test/runtests.jl, test/windows_java.sh
Squashed commit of the following:
commit 8dbbcdcbd66c5f86cf8b5be05f45d92b56f128f5
Author: Mark Kittisopikul <mark.kittisopikul@utsouthwestern.edu>
Date:   Fri Mar 6 21:29:18 2020 -0600
Enable JULIA_COPY_STACKS=0 on mac
commit b9b89ee385ffd8af9e07889af0b75191f4f891de
Author: Mark Kittisopikul <mark.kittisopikul@utsouthwestern.edu>
Date:   Fri Mar 6 19:43:35 2020 -0600
Reduce testing
commit 21b01981e35b9b7536e0e1edd2a7ae492bb66074
Author: Mark Kittisopikul <mark.kittisopikul@utsouthwestern.edu>
Date:   Fri Mar 6 17:58:42 2020 -0600
Configure forced async tests
commit c9c3051f71619ea012cb50bd44189a5890043fc7
Author: Mark Kittisopikul <mark.kittisopikul@utsouthwestern.edu>
Date:   Fri Mar 6 17:39:43 2020 -0600
Don't expect exception on Windows
commit 2df1c844f0d329b6e3e43f8181fb797bc2655f27 …
=> Check for Windows OS or JULIA_COPY_STACKS on jcall, improve testing

src/jvm.jl
Resolve the path of the `java` command to determine where the default java installation is.
=> Find javahome on unix by checking location of the java command

doc/index.md
that you may want to include in docs..
Security issues may or may not apply to Java use of Julia programs..
Not sure if "http://docs.oracle.com/javase/1.5.0" .. is most recent doc.
[skip ci]
=> Upper case "Java" and security notice..

src/core.jl
This change makes it easier to construct objects that require no arguments.
```
julia> using JavaCall
[ Info: Precompiling JavaCall [494afd89-becb-516b-aafa-70d2670c0337]
┌ Warning: JavaCall needs the environment variable `JULIA_COPY_STACKS` to be `1` or `yes`.
│ Calling the JVM may result in undefined behavior.
└ @ JavaCall ~/.julia/dev/JavaCall/src/JavaCall.jl:42
julia> JavaCall.addClassPath.(["jars/*","plugins/*"]); JavaCall.init()
julia> ImageJ2 = @jimport net.imagej.ImageJ
JavaObject{Symbol("net.imagej.ImageJ")}
julia> ImageJ1 = @jimport ij.ImageJ
JavaObject{Symbol("ij.ImageJ")}
julia> ImageJ2()
JavaObject{Symbol("net.imagej.ImageJ")}(Ptr{Nothing} @0x0000560b5e6c5298)
julia> ImageJ1()
JavaObject{Symbol("ij.ImageJ")}(Ptr{Nothing} @0x0000560b5e6c52a8)
```
Otherwise, we have to use the …
=> Add a no argument constructor for JavaObjects

doc/index.md, src/jvm.jl
Rather than `path/*` and `path/*.jar` doing the same thing, this alters the functionality such that `path/*`  recursively adds directories and jars in the `path` directory. `path/*.jar` only adds in the jar files.
=> addClassPathRecursive

src/jvm.jl
This is an update of #89 that avoids the use of the undocumented `Base.Filesystem.path_separator` but instead uses `splitdir` and `joinpath` to constructed a path on either Windows or *nix
=> OS agnostic addClassPath

doc/methods.md, src/jvm.jl
corrected an error with the .* syntax in Windows systems in addClassPath. Also added the *.jar syntax to the addClassPath function for ease of use.
Added a paragraph to the documentation regarding the proper use of addClassPath and init().
Hope this is better now :-)
=> addClassPath .* and *.jar syntax

src/JavaCall.jl, src/convert.jl, src/core.jl, src/jnienv.jl, src/jnienv2.jl, src/make_jni2.jl
I was planning to look at how arrays are handled, but I found the ccall syntax hard to use.  I got distracted and wrote this.  It's basically a submodule with methods wrapping most JNI functions.
Instead of
`realClass = ccall(jnifunc.GetObjectClass, Ptr{Void}, (Ptr{JNIEnv}, Ptr{Void} ), penv, obj.ptr)`
you can write
`realClass = GetObjectClass(penv, obj.ptr)`
GetObjectClass is defined as
`GetObjectClass(env::Ptr{JNIEnv}, obj::jobject) = ccall(jnifunc.GetObjectClass, jclass, (Ptr{JNIEnv}, jobject,), env, obj)`
It's not perfect, but I think it's already an improvement.  It's mostly auto-generated from the comments in jnienv.jl.  The test suite passes, but most of these methods aren't exercised.
Since I don't know how much time I'll have to work on this coming up, I thought I should push it …
=> JNI methods

.travis.yml, Project.toml, src/JNI.jl, src/JavaCall.jl, src/convert.jl, src/core.jl, src/jnienv.jl, src/make_jni2.jl, test/runtests.jl, test/windows_java.sh
Currently all Java references to objects in JavaCall are "local" Java references for variables that are only meant to live the lifetime of a Java method call after which the Java garbage collector may free the underlying memory. Because the use of these references in JavaCall is occurring outside of the context of a Java method call, currently the local references are never marked for garbage collection. The local part of a Java method call can emulated by the use of `JNI.PopLocalFrame` and `JNI.PushLocalFrame`.
However, there are some are some references that we would not like to mark for collection, notably the metaclasses. The JNI also has the concept of global references that are meant to survive a Java method call.
To improve memory management, I create a new family of types, …
=> Create JavaRef, JavaLocalRef, and JavaGlobalRef to hold references and manage memory

src/convert.jl
=> Fix memory leak for primitive array

JProxies/README.md
I made a small readme with links to the original files for history.
=> adding readme to point to JProxy file history

src/reflect.jl
While working in a university project we stumbled upon this bug.
Co-authored-by: João David <joaodavid@tecnico.ulisboa.pt>
=> Add support for short to conventional_name

src/core.jl, test/runtests.jl
The main purpose of this PR is to make it easier to extend JavaCall with types that e.g. need special cleanup, define a `signature` method, etc. (see #144).
Since the relevant logic to handle the core call through `JNI` was spread out, discrepancies had crept into the codebase:
https://github.com/JuliaInterop/JavaCall.jl/blob/7973dc760fc8b3fdd07baf763cf27b515d199e88/src/core.jl#L485
https://github.com/JuliaInterop/JavaCall.jl/blob/7973dc760fc8b3fdd07baf763cf27b515d199e88/src/core.jl#L458
So:
```
julia> jcall(JavaObject{Symbol("java.util.HashMap")}(C_NULL), "toString", JString, ())
ERROR: Attempt to call method on Java NULL
Stacktrace:
...
julia> jcall(JavaObject{Symbol("java.util.HashMap")}(C_NULL), "isEmpty", jboolean, ())
ERROR: JavaCall.JavaCallError("Attempt to call method on Java …
```
=> Consolidate jcall to enable extension of JVM types

src/JavaCall.jl, src/core.jl, src/jniarray.jl, src/reflect.jl, test/runtests.jl
After the discussion in #134 I've experimented with approaches to exposing more of the JNI array functionality. Here is the draft for one such approach so that we can discuss whether this direction is of interest for JavaCall.
This would be a very lightweight approach to exposing the JNI array functionality where the user can choose to keep a returned array as a pointer and get and set elements directly through an `unsafe_wrap` array.
There are also some parts of JProxies that point in this direction but they are less lightweight with a different interface from the rest of JavaCall. I couldn't get them to do exactly what I want. However, if you think the JProxies approach is a better direction I'd be glad to help to surface this functionality through documentation and/or changes to …
=> Raw JNI arrays

src/jniarray.jl, test/runtests.jl
Fixes:
1. Explicitly set  `own = false` with `unsafe_wrap` since Java should free the array, not Julia
2. Make sure the JVM has not been destroyed before we to call `Release*`
cc: @ahnlabb
=> Fix JNIVector garbage collection, check if JVM destroyed

src/convert.jl
It was observed that JavaCall was leaking memory when getting arrays of objects from Java. This is due to the fact that arrays from Java are converted into Julia arrays by copying the elements over from the Java array, but the Java array is subsequently not freed from memory, causing a leak as at the end of the Julia code the pointer is garbage collected.  In #135  essentially the same leak was fixed, but only for primitive arrays, not arrays of Java objects, etc. This PR aims to solve the issue for the remaining cases.
=> Fix JNI array leaking by freeing the memory after conversion
